---
name: Plan - Network

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/network/*'
      - 'terraform/network/**'
      - '.github/workflows/plan-network.yaml'
      - '.github/workflows/reusable-ci-workflow.yaml'
  workflow_dispatch:

jobs:
  ## run terraform plan
  plan_poc:
    name: Network
    uses: "./.github/workflows/reusable-ci-workflow.yaml"
    with:
      working_directory: network
      environment: poc
      assume_role_name: ""
      aws_region: us-east-1
      publish_plan_artifact: false  # only for apply step
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
