---
name: Plan - SQS

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/sqs/*'
      - 'terraform/sqs/**'
      - '.github/workflows/plan-sqs.yaml'
      - '.github/workflows/reusable-ci-workflow.yaml'
  workflow_dispatch:

jobs:
  ## run terraform plan
  plan_poc:
    name: SQS
    uses: "./.github/workflows/reusable-ci-workflow.yaml"
    with:
      working_directory: sqs
      environment: poc
      assume_role_arn: ""
      aws_region: us-east-1
      publish_plan_artifact: false  # only for apply step
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
