---
name: snyk

on:              # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"       # matches every branch
      - "!main"    # excludes main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    runs-on:
      - self-hosted
      - arc
    name: snyk
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Vulnerability scan
        uses: snyk/actions/iac@master
        with:
          command: monitor
          args: --severity-threshold=low

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install Snyk CLI
        run: npm install -g snyk

      - name: snyk monitor
        run: snyk iac test --report --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.ARC_SNYK_TOKEN }}
